import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'p-aqua-daily',
    slug: 'aqua-daily-clear',
    name: 'Aqua Daily Clear',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'clear',
    replacement: 'daily',
    description:
      'Ultra-breathable daily disposable lenses with high moisture retention for all-day comfort.',
    images: ['/images/products/aqua-daily-1.jpg', '/images/products/aqua-daily-2.jpg'],
    badges: ['bestseller'],
    specs: {
      material: 'Silicone Hydrogel',
      waterContent: '55%',
      baseCurve: '8.6mm',
      diameter: '14.2mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-aqua-daily-30',
        sku: 'AQD-30',
        packSize: '30 lenses',
        price: 25,
        currency: 'USD',
        stock: 120,
      },
      {
        id: 'p-aqua-daily-90',
        sku: 'AQD-90',
        packSize: '90 lenses',
        price: 65,
        compareAtPrice: 75,
        currency: 'USD',
        stock: 60,
      },
    ],
    rating: 4.6,
    reviewCount: 2,
  },
  {
    id: 'p-breeze-daily',
    slug: 'breeze-daily-clear',
    name: 'Breeze Daily Clear',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'clear',
    replacement: 'daily',
    description:
      'Lightweight daily lenses engineered for sensitive eyes, with a smooth, low-profile edge design.',
    images: ['/images/products/breeze-daily-1.jpg', '/images/products/breeze-daily-2.jpg'],
    badges: ['new'],
    specs: {
      material: 'Hydrogel',
      waterContent: '58%',
      baseCurve: '8.7mm',
      diameter: '14.0mm',
      uvProtection: false,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-breeze-daily-30',
        sku: 'BRZ-30',
        packSize: '30 lenses',
        price: 22,
        currency: 'USD',
        stock: 90,
      },
    ],
    rating: 4.4,
    reviewCount: 0,
  },
  {
    id: 'p-ocean-biweekly',
    slug: 'ocean-biweekly-clear',
    name: 'Ocean Biweekly Clear',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'clear',
    replacement: 'biweekly',
    description:
      'Reusable biweekly lenses offering consistent clarity and reliable hydration between replacements.',
    images: ['/images/products/ocean-biweekly-1.jpg', '/images/products/ocean-biweekly-2.jpg'],
    badges: [],
    specs: {
      material: 'Silicone Hydrogel',
      waterContent: '52%',
      baseCurve: '8.6mm',
      diameter: '14.2mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-ocean-biweekly-6',
        sku: 'OCB-6',
        packSize: '6 lenses',
        price: 28,
        currency: 'USD',
        stock: 70,
      },
    ],
    rating: 4.3,
    reviewCount: 0,
  },
  {
    id: 'p-hazel-monthly',
    slug: 'hazel-monthly-colored',
    name: 'Hazel Monthly Colored',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'colored',
    replacement: 'monthly',
    description:
      'Monthly colored lenses with a natural gradient pattern for a subtle, everyday enhancement.',
    images: ['/images/products/hazel-monthly-1.jpg', '/images/products/hazel-monthly-2.jpg'],
    badges: [],
    specs: {
      material: 'Hydrogel',
      waterContent: '48%',
      baseCurve: '8.6mm',
      diameter: '14.5mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-hazel-monthly-brown-10',
        sku: 'HZM-BR-10',
        color: 'brown',
        colorLabel: 'Hazel Brown',
        packSize: '10 lenses',
        price: 20,
        currency: 'USD',
        stock: 50,
      },
      {
        id: 'p-hazel-monthly-brown-30',
        sku: 'HZM-BR-30',
        color: 'brown',
        colorLabel: 'Hazel Brown',
        packSize: '30 lenses',
        price: 48,
        currency: 'USD',
        stock: 30,
      },
      {
        id: 'p-hazel-monthly-gray-10',
        sku: 'HZM-GR-10',
        color: 'gray',
        colorLabel: 'Storm Gray',
        packSize: '10 lenses',
        price: 20,
        currency: 'USD',
        stock: 45,
      },
      {
        id: 'p-hazel-monthly-gray-30',
        sku: 'HZM-GR-30',
        color: 'gray',
        colorLabel: 'Storm Gray',
        packSize: '30 lenses',
        price: 48,
        currency: 'USD',
        stock: 25,
      },
    ],
    rating: 4.7,
    reviewCount: 0,
  },
  {
    id: 'p-mystic-daily',
    slug: 'mystic-daily-colored',
    name: 'Mystic Daily Colored',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'colored',
    replacement: 'daily',
    description:
      'Daily colored lenses with vivid pigmentation, currently on sale for a limited time.',
    images: ['/images/products/mystic-daily-1.jpg', '/images/products/mystic-daily-2.jpg'],
    badges: ['sale'],
    specs: {
      material: 'Hydrogel',
      waterContent: '50%',
      baseCurve: '8.6mm',
      diameter: '14.2mm',
      uvProtection: false,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-mystic-daily-violet-10',
        sku: 'MYS-VI-10',
        color: 'violet',
        colorLabel: 'Mystic Violet',
        packSize: '10 lenses',
        price: 18,
        compareAtPrice: 24,
        currency: 'USD',
        stock: 40,
      },
      {
        id: 'p-mystic-daily-violet-30',
        sku: 'MYS-VI-30',
        color: 'violet',
        colorLabel: 'Mystic Violet',
        packSize: '30 lenses',
        price: 45,
        compareAtPrice: 58,
        currency: 'USD',
        stock: 20,
      },
    ],
    rating: 4.5,
    reviewCount: 0,
  },
  {
    id: 'p-torica-monthly',
    slug: 'torica-monthly-toric',
    name: 'Torica Monthly Toric',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'toric',
    replacement: 'monthly',
    description:
      'Monthly toric lenses designed for astigmatism, with stabilized rotation control for sharp vision.',
    images: ['/images/products/torica-monthly-1.jpg', '/images/products/torica-monthly-2.jpg'],
    badges: [],
    specs: {
      material: 'Silicone Hydrogel',
      waterContent: '46%',
      baseCurve: '8.7mm',
      diameter: '14.5mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-torica-monthly-6',
        sku: 'TRM-6',
        packSize: '6 lenses',
        price: 38,
        currency: 'USD',
        stock: 35,
      },
    ],
    rating: 4.2,
    reviewCount: 0,
  },
  {
    id: 'p-torica-biweekly',
    slug: 'torica-biweekly-toric',
    name: 'Torica Biweekly Toric',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'toric',
    replacement: 'biweekly',
    description:
      'Biweekly toric lenses offering precise astigmatism correction and consistent all-day comfort.',
    images: [
      '/images/products/torica-biweekly-1.jpg',
      '/images/products/torica-biweekly-2.jpg',
    ],
    badges: [],
    specs: {
      material: 'Silicone Hydrogel',
      waterContent: '47%',
      baseCurve: '8.6mm',
      diameter: '14.3mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-torica-biweekly-6',
        sku: 'TRB-6',
        packSize: '6 lenses',
        price: 32,
        currency: 'USD',
        stock: 40,
      },
    ],
    rating: 4.1,
    reviewCount: 0,
  },
  {
    id: 'p-focalpro-monthly',
    slug: 'focalpro-monthly-multifocal',
    name: 'Focalpro Monthly Multifocal',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'multifocal',
    replacement: 'monthly',
    description:
      'Monthly multifocal lenses providing seamless near and far vision correction for presbyopia.',
    images: [
      '/images/products/focalpro-monthly-1.jpg',
      '/images/products/focalpro-monthly-2.jpg',
    ],
    badges: [],
    specs: {
      material: 'Silicone Hydrogel',
      waterContent: '45%',
      baseCurve: '8.7mm',
      diameter: '14.4mm',
      uvProtection: true,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-focalpro-monthly-6',
        sku: 'FPM-6',
        packSize: '6 lenses',
        price: 42,
        currency: 'USD',
        stock: 30,
      },
    ],
    rating: 4.4,
    reviewCount: 0,
  },
  {
    id: 'p-focalpro-daily',
    slug: 'focalpro-daily-multifocal',
    name: 'Focalpro Daily Multifocal',
    brandId: 'vivimoon',
    brandName: 'Vivimoon',
    type: 'multifocal',
    replacement: 'daily',
    description:
      'Daily disposable multifocal lenses for effortless presbyopia correction without the upkeep.',
    images: ['/images/products/focalpro-daily-1.jpg', '/images/products/focalpro-daily-2.jpg'],
    badges: [],
    specs: {
      material: 'Hydrogel',
      waterContent: '54%',
      baseCurve: '8.6mm',
      diameter: '14.2mm',
      uvProtection: false,
      manufacturer: 'Vivimoon Labs',
    },
    variants: [
      {
        id: 'p-focalpro-daily-30',
        sku: 'FPD-30',
        packSize: '30 lenses',
        price: 36,
        currency: 'USD',
        stock: 50,
      },
    ],
    rating: 4.3,
    reviewCount: 0,
  },
];
